# Generated by Django 4.2 on 2023-04-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Phone name')),
                ('price', models.PositiveBigIntegerField(verbose_name='Phone price')),
            ],
        ),
    ]
