# Generated by Django 4.2 on 2023-04-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nout name')),
                ('price', models.PositiveBigIntegerField(verbose_name='Nout price')),
            ],
        ),
    ]
