# Generated by Django 4.2 on 2023-04-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nout'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='img',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Phone image'),
        ),
    ]
